### ISSUE TITLE
Redefine deploy action for CI/CD

### ISSUE THREAD

**Issue by erlendoksvoll** [data-altinn-no/core#130]
### Description

Make sure steps are run in correct order - deploy-> test, gate and so on - consider making separate workflow for core instead of using the same flow for plugins AND core

### Steps To Reproduce

Deploy

**Comment by SondreJDigdir** [comment]
Consider further improvements on the CI/CD pipelines later. But Core now has its own pipeline, it's basically the same as before, but we can now make changes to it without worrying about breaking anything for the plugins, and vice versa.
